--- #YAML:1.0
name:               DBIx-Class-Tree-NestedSet
version:            0.10
abstract:           Manage trees of data using the nested set model
author:
    - Ian Docherty <cpan@icydee.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBICx::TestDatabase:  0.01
    DBIx::Class:          0.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
